### ISSUE TITLE
support for activemq?

### ISSUE THREAD

**Issue by erickyi2006** [zuazo/node-jmx#14]
I managed to made several calls in activemq.
1. getAttribute
2. invoke ("browse")
3. invoke("getMessage")

getAttribute works find but browse and getMessage does not work (partial work)
partial because it browse() returns an array of object but the object is empty {}. Ditto for getMessage(). 

I think the conversion is not done correctly. I put a trace to getMessage and saw it returns this object type "nodeJava_javax_management_openmbean_CompositeDataSupport". how do I get this to work.

**Comment by erickyi2006** [comment]
Got it working now. Thanks to Joe Ferner from node_java
Must use data.toStringSync().

**Comment by zuazo** [comment]
OK, thank you @erickyi2006

Related issue: https://github.com/joeferner/node-java/issues/371
